#!/usr/bin/env python3
"""
Evaluate router-v2 on the actual MedHop validation split.

Loads the trained model, loads validation features and labels, and reports metrics.
"""

import json
import numpy as np
import joblib
from pathlib import Path
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def main():
    output_dir = Path(__file__).parent

    labels_file = output_dir / "labels_validation.json"
    if not labels_file.exists():
        print("ERROR: labels_validation.json not found.")
        print("This file is required to evaluate validation performance.")
        print("To generate it, run generate_labels_hybrid.py on the validation split.")
        print("(This file is not generated by default — it's only needed for offline eval.)")
        return

    print("Loading model and threshold...")
    model_data = joblib.load(output_dir / "model.pkl")
    scaler = model_data["scaler"]
    lr = model_data["lr"]

    with open(output_dir / "threshold.json") as f:
        threshold = json.load(f)["threshold"]

    print(f"Threshold: {threshold}")

    print("Loading validation features and labels...")
    features = np.load(output_dir / "features_validation.npz", allow_pickle=True)
    X_val = features["X"]
    ids_val = features["ids"]

    with open(labels_file) as f:
        labels_dict = json.load(f)

    valid_indices = []
    y_val_list = []

    for i, example_id in enumerate(ids_val):
        if example_id in labels_dict:
            valid_indices.append(i)
            y_val_list.append(labels_dict[example_id])

    X_val = X_val[valid_indices]
    y_val = np.array(y_val_list, dtype=np.int32)

    print(f"Validation set: {len(y_val)} examples")
    label_counts = np.bincount(y_val)
    class0_count = label_counts[0]
    class1_count = label_counts[1] if len(label_counts) > 1 else 0
    print(f"  Class 0 (single): {class0_count} ({class0_count/len(y_val)*100:.1f}%)")
    print(f"  Class 1 (multi):  {class1_count} ({class1_count/len(y_val)*100:.1f}%)")

    print("\nEvaluating...")
    X_val_scaled = scaler.transform(X_val)
    probs = lr.predict_proba(X_val_scaled)[:, 1]
    y_pred = (probs >= threshold).astype(int)

    acc = accuracy_score(y_val, y_pred)
    prec = precision_score(y_val, y_pred, zero_division=0)
    rec = recall_score(y_val, y_pred, zero_division=0)
    f1 = f1_score(y_val, y_pred, zero_division=0)
    cm = confusion_matrix(y_val, y_pred)

    print(f"\n--- Validation Results (Threshold = {threshold}) ---")
    print(f"  Accuracy:  {acc*100:.1f}%")
    print(f"  Precision: {prec*100:.1f}%")
    print(f"  Recall:    {rec*100:.1f}%")
    print(f"  F1:        {f1*100:.1f}%")
    print(f"  Confusion matrix:\n{cm}")

    results = {
        "threshold": threshold,
        "validation_accuracy": round(acc, 4),
        "validation_precision": round(prec, 4),
        "validation_recall": round(rec, 4),
        "validation_f1": round(f1, 4),
        "n_val_examples": int(len(y_val)),
        "confusion_matrix": cm.tolist(),
    }

    with open(output_dir / "results_val.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved results → results_val.json")

if __name__ == "__main__":
    main()
